language: php

sudo: false

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 8.0
  - hhvm

before_script:
  - composer self-update || true
  - composer install

cache:
  directories:
    - vendor
    - $COMPOSER_CACHE_DIR
